### ISSUE TITLE
Suggestion: how about Pause and Restart timer 

### ISSUE THREAD

**Issue by ihatecodinglikeking** [Ayesh/php-timer#5]
Hey NICE work!!! 
Whats your thought on having Pause and Restart particular timer?

**Comment by Ayesh** [comment]
Thanks @ihatecodinglikeking 
The `stop` method does not clear the timer, so the second `start` calls will resume the timer, making the start-stop actions work as a pause-resume operation. 

As tested in https://github.com/Ayesh/php-timer/blob/ccf6040eba2617eedfe137b2ae2c47f36a4738ec/tests/TimerTest.php#L90-L101 ,  Calling `start` on a running timer will not throw any errors either.
