### ISSUE TITLE
Switch Code Style 

### ISSUE THREAD

**Issue by atymic** [Ayesh/php-timer#7]
I had to adjust a bunch of setting before I was able to make as PR as the library uses non-standard indenting/code style.

I'd suggest using the PSR2 standard. If you don't want to, we should at least add an editorconfig file so indenting/etc are automatically configured :)

**Comment by Ayesh** [comment]
Thanks for raising this issue, @atymic. I have added a new `.editorconfig` file and a round of code cleanup. So far, we are using 2-space indenting, LF line endings, and an empty line at the end of the file. Please feel free to suggest any optimizations there if you notice any.

**Comment by atymic** [comment]
No worries. I was suggesting using PSR2, which is the standard and generally how most people write PHP code:
https://www.php-fig.org/psr/psr-2/

You can use tools like styleci or phpcs to lint and fix issues automatically :)
